# Generated by Django 5.2 on 2025-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favouites',
            field=models.ManyToManyField(default=list, null=True, related_name='profiles', to='home.movie'),
        ),
    ]
