# Generated by Django 5.2 on 2025-04-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_favouites'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favouites',
            field=models.ManyToManyField(default=list, related_name='profiles', to='home.movie'),
        ),
    ]
