# Generated by Django 5.2 on 2025-04-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_favouites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favouites',
            new_name='favourites',
        ),
    ]
