# Generated by Django 5.2 on 2025-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_avatar_url'),
        ('home', '0015_movie_budget_movie_revenue_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_casts',
            field=models.ManyToManyField(related_name='profiles', to='home.cast'),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstTime_login_done',
            field=models.BooleanField(default=False),
        ),
    ]
