# Generated by Django 5.2.4 on 2025-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_fav_casts_profile_firsttime_login_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watched_episodes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
