# Generated by Django 5.2 on 2025-04-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
