# Generated by Django 5.2 on 2025-04-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_movie_populaity_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='populaity',
            new_name='popularity',
        ),
    ]
