# Generated by Django 5.2 on 2025-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_movie_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='in_slider',
            field=models.BooleanField(default=False),
        ),
    ]
