# Generated by Django 5.2 on 2025-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_movie_in_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
