# Generated by Django 5.2 on 2025-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
