# Generated by Django 5.2 on 2025-04-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_movie_backdrop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
