# Generated by Django 5.2 on 2025-04-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cast_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
