# Generated by Django 5.2 on 2025-04-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_cast_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
    ]
