# Generated by Django 5.2 on 2025-04-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_movie_imdb_rating_movie_imdb_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
