# Generated by Django 5.2 on 2025-04-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_movie_budget_movie_revenue_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='in_option',
            field=models.BooleanField(default=False),
        ),
    ]
