# Generated by Django 5.2 on 2025-08-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_cast_in_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='episodes_per_season',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='no_of_episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='no_of_seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
