# Generated by Django 5.2.4 on 2025-08-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_movie_content_type_movie_episodes_per_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('plot', models.TextField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('runtime', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='home.movie')),
            ],
        ),
    ]
